Ques1:Convert the below list into numpy array then display the array

Input:my_list=[1,2,3,4,5]

In [1]:
import numpy as np
my_list=[1,2,3,4,5]
print("Input list is:",my_list)
a=np.array(my_list)
print("conversion of list into array:",a)

Input list is: [1, 2, 3, 4, 5]
conversion of list into array: [1 2 3 4 5]


Ques2: Convert the below list into a numpy array then display the array then display the first and last index and then multiply each element by 2 and displaqy the result.

Input:my_list=[1,2,3,4,5]


In [2]:
import numpy as np
my_list=[1,2,3,4,5]
print("Input list is:",my_list)
a=np.array(my_list)
print("Converted array is:",a)
b=a[0]
c=a[-1]
print("Fisrt index element is:",b)
print("Last index array is:",c)
print("Array after multiplying by 2:",a*2)

Input list is: [1, 2, 3, 4, 5]
Converted array is: [1 2 3 4 5]
Fisrt index element is: 1
Last index array is: 5
Array after multiplying by 2: [ 2  4  6  8 10]


Ques: Write a numpy program to create an array of 10 zeros ,10 ones and 10 fives

output:

An array of 10 zeros:

[0 . 0. 0. 0. 0. 0. 0. 0. 0. 0.]

An array of 10 ones

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. ]

An array of 10 fives

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. ]

In [3]:
import numpy as np
a=np.zeros(10)
print("An array of 10 zeros")
print(a)
b=np.ones(10)
print("An array of 10 ones")
print(b)
c=np.full(10,5,dtype=float)
print("An array of 10 fives")
print(c)

An array of 10 zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Ques:Write a numpy program to create a 3*3 matrix with values ranging from 2 to 10

In [4]:
import numpy as np
mat=np.arange(2,11).reshape(3,3)
print(mat)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Ques:Calculate the total revenue generated by two product categories in a store

Input

category1_revenue=np.array([500,600,700,550])

category2_revenue=np.array([450,700,800,600])

Total Revenue=[950 1300 1500 1150]

In [5]:
import numpy as np
category1_revenue=np.array([500,600,700,550])
print("Revenue generated by category 1:",category1_revenue)
category2_revenue=np.array([450,700,800,600])
print("Revenue generated by category 2:",category2_revenue)
total_revenue=category1_revenue + category2_revenue
print("Total Revenue:",total_revenue)

Revenue generated by category 1: [500 600 700 550]
Revenue generated by category 2: [450 700 800 600]
Total Revenue: [ 950 1300 1500 1150]


Ques2:Calculate the profit made by a company.

Input:

revenue=np.array([10000,12000,11000,10500])

expenses=np.array([4000,5000,4500,4800])

Profit:[6000 7000 6500 5700]

In [6]:
import numpy as np
revenue=np.array([10000,12000,11000,10500])
print("Revenue generated is:",revenue)
expenses=np.array([4000,5000,4500,4800])
print("Total expenses are:",expenses)
profit=revenue-expenses
print("Profit:",profit)

Revenue generated is: [10000 12000 11000 10500]
Total expenses are: [4000 5000 4500 4800]
Profit: [6000 7000 6500 5700]


Ques:Determine which products in a store are out of stock(quantity is 0)

Input:

inventory=np.array([10,0,5,0,20,0])

output:

Out of stock Products:[0 0 0]

In [7]:
import numpy as np
inventory=np.array([10,0,5,0,20,0])
print("Products in inventory are:",inventory)
out_of_stock_products=inventory[inventory==0]
print("Out of stock Products:",out_of_stock_products)

Products in inventory are: [10  0  5  0 20  0]
Out of stock Products: [0 0 0]


Ques: Calculate the total cost of items in a shopping cart , considering the quantity and price per item

Input:

quantity=np.array([2,3,4,1])
price_per_item=np.array({10.0,5.0,8.0,12.0])

output:

Total cost of items:[20. 15. 32. 12.

In [8]:
import numpy as np
quantity = np.array([2, 3, 4, 1])
print("Quantity of items is:",quantity)
price_per_item = np.array([10.0, 5.0, 8.0, 12.0])
print("price per items is:",price_per_item)
Total_cost_of_items=quantity*price_per_item
print("Total cost of items:",Total_cost_of_items)

Quantity of items is: [2 3 4 1]
price per items is: [10.  5.  8. 12.]
Total cost of items: [20. 15. 32. 12.]
